# Generated by Django 3.2.13 on 2022-06-27 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранный рецепт'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингридиент'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredientqty',
            options={'verbose_name': 'Ингридиент рецепта'},
        ),
        migrations.AlterModelOptions(
            name='shopping',
            options={'verbose_name': 'Рецепт в корзине'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время готовки, мин.'),
        ),
    ]
